### PR TITLE
Remove Lagom version detection

### LINKED ISSUE #136: Lagom 1.5 compatibility
We're getting ready to release the first milestone of Lagom 1.5.0.

Currently, `sbt-reactive-app` causes resolution failures when you add it to a project using 1.5.0-SNAPSHOT:

```
[warn]       ::::::::::::::::::::::::::::::::::::::::::::::
[warn]       ::          UNRESOLVED DEPENDENCIES         ::
[warn]       ::::::::::::::::::::::::::::::::::::::::::::::
[warn]       :: com.lightbend.rp#reactive-lib-service-discovery-lagom15-scala_2.12;0.9.0: not found
[warn]       ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]       Note: Unresolved dependencies path:
[warn]               com.lightbend.rp:reactive-lib-service-discovery-lagom15-scala_2.12:0.9.0
[warn]                 +- com.example:hello-k8s-stream-impl_2.12:1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.lightbend.rp#reactive-lib-service-discovery-lagom15-scala_2.12;0.9.0: not found
```

This is because `sbt-reactive-app` tries to add a dependency to the project based on the detected Lagom version:

https://github.com/lightbend/sbt-reactive-app/blob/f76a97679e558492a57e79cbb459b60cd2306d54/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala#L136-L168

The patterns `reactive-lib-service-discovery-lagom${SemVer.formatMajorMinor(v)}-java` and `reactive-lib-service-discovery-lagom${SemVer.formatMajorMinor(v)}-scala` are only successful for Lagom 1.4.x versions, because the only Lagom service discovery modules defined in `reactive-lib` are `service-discovery-lagom14-java` and `service-discovery-lagom14-scala`.

While we could create `service-discovery-lagom15-java` and `service-discovery-lagom15-scala` modules, at this time there's no reason for these to be different from the 1.4 versions, so instead I suggest hardcoding the "14" version and removing the version-detection part.

Eventually, I think the Lagom-specific service locator code can move into the lagom/lagom project (possibly before 1.5.0) and we can remove the service locator from `reactive-lib` in favor of [Akka Service Discovery](https://developer.lightbend.com/docs/akka-management/current/discovery.html).

(I'll submit a pull request for this.)

### PR DESCRIPTION
**Pull request by TimMoore**
Fixes #136

In line with my recommendation there, my approach was to remove all of the code that tries to detect the Lagom version, and simply hardcode dependencies on `reactive-lib-service-discovery-lagom14-java` and `reactive-lib-service-discovery-lagom14-scala`, the only versions that currently exist, and the only ones we anticipate needing.

The implementation is complete, and I'm opening a pull request now to get early feedback from people in other time zones, but there's still more testing that I'll need to do tomorrow.

- [x] Test `sbt runAll` with Lagom 1.5.0-SNAPSHOT
- [x] Test Kubernetes deployment with Lagom 1.5.0-SNAPSHOT
- [x] Regression test `sbt runAll` with Lagom 1.4.7
- [x] Regression test Kubernetes deployment with Lagom 1.4.7

(Of course, if anyone else wants to help test some of these, please go right ahead.)

### CODE REVIEW

File: src/main/scala/com/lightbend/rp/sbtreactiveapp/magic/Lagom.scala [hunk 1]
```diff
@@ -88,19 +88,6 @@ object Lagom {
     }
   }
 
-  def version: Option[String] = {
```
Comment (dwijnand) [inline src/main/scala/com/lightbend/rp/sbtreactiveapp/magic/Lagom.scala]: Looks like this is public (binary) API. Let's just deprecate it instead of deleting it.

**Comment by dwijnand** [comment]
LGTM. Just a binary API concern.

File: src/main/scala/com/lightbend/rp/sbtreactiveapp/magic/Lagom.scala (hunk 1 above)
Comment (TimMoore) [reply src/main/scala/com/lightbend/rp/sbtreactiveapp/magic/Lagom.scala]: Oh… why is any of this class public API? 😕

Comment (TimMoore) [reply src/main/scala/com/lightbend/rp/sbtreactiveapp/magic/Lagom.scala]: Should I bump version to 1.4.0-SNAPSHOT if I'm deprecating APIs?

Comment (dwijnand) [reply src/main/scala/com/lightbend/rp/sbtreactiveapp/magic/Lagom.scala]: Sure.

**Comment by TimMoore** [comment]
I restored and deprecated the `magic.Lagom.version` method, bumped the version to `1.4.0-SNAPSHOT`, and went through the four tests outlined above. Everything looks good to me.

I noticed that the build passed originally despite the binary compatibility issue, so I raised #139 to add MiMa.

**Comment by TimMoore** [comment]
Ready to merge if you are @dwijnand.
